# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool: myUbuntuAgentsPool

steps:
- script: java --version
  displayName: 'Run a one-line script'
