# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: linuxMachineOne

steps:
# - task: DockerInstaller@0
#   inputs:
#     dockerVersion: '17.09.0-ce'

# - script: sudo service docker start
#   displayName: 'start docker demon'

# - task: Docker@2
#   inputs:
#     command: 'start'
#     container: 'hello-world'

# - task: NodeTool@0
#   inputs:
#     versionSource: 'spec'
#     versionSpec: '6.x'
#     checkLatest: true

# - script: node --version
#   displayName: 'check node'

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: |
#       # Write your commands here
      
#       docker --version
# - script: java --version
#   displayName: 'Run a one-line script'

- script: echo 'hello world'
  displayName: 'check node'

# - script: docker run hello-world
#   displayName: 'run one image of docker'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      sudo service docker start
      sudo docker run hello-world
